# Generated by Django 2.0.1 on 2018-03-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='valuename',
        ),
    ]
