# Generated by Django 2.0.1 on 2018-03-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0002_remove_setting_valuename'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='valuename',
            field=models.CharField(choices=[('TELETOKEN', 'Telegram Token')], default='TELETOKEN', max_length=100),
        ),
    ]
