# Generated by Django 2.0.1 on 2018-03-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0004_auto_20180328_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_session',
            name='status',
            field=models.BigIntegerField(verbose_name='Статус'),
        ),
    ]
