# Generated by Django 2.0.1 on 2018-05-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0009_auto_20180401_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(null='False')),
                ('status', models.BigIntegerField(null='False')),
                ('job_name', models.CharField(blank='False', max_length=1000, null='False', verbose_name='Название Джоба')),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='valuename',
            field=models.CharField(choices=[('TELETOKEN', 'Telegram Token'), ('FSSPTOKEN', 'FSSP Token'), ('VIBERTOKEN', 'VIBER Token'), ('SYSDEFAULT', 'Default Messanger')], default='TELETOKEN', max_length=100),
        ),
    ]
