# Generated by Django 2.0.5 on 2018-07-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0012_auto_20180511_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='valuename',
            field=models.CharField(choices=[('TELETOKEN', 'Telegram Token'), ('FSSPTOKEN', 'FSSP Token'), ('VIBERTOKEN', 'VIBER Token'), ('SYSDEFAULT', 'Default Messenger')], default='TELETOKEN', max_length=100),
        ),
    ]
