# Generated by Django 2.0.5 on 2018-07-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0013_auto_20180715_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data',
            field=models.CharField(blank='False', max_length=1000, null='False', verbose_name='DATA'),
        ),
    ]
