# Generated by Django 2.0.5 on 2018-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsspbotdb', '0014_job_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank=True, null='True'),
        ),
    ]
